ALTER TABLE tasks ADD COLUMN IF NOT EXISTS start_date DATETIME DEFAULT NULL AFTER assigned_to;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS depends_on INT DEFAULT NULL AFTER deadline;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS progress INT DEFAULT 0 AFTER depends_on;
ALTER TABLE tasks ADD INDEX IF NOT EXISTS idx_depends_on (depends_on);
