-- Git-based deploy targets (replaces SFTP upload model)
ALTER TABLE remote_deploy_configs
  ADD COLUMN repo_url VARCHAR(500) DEFAULT NULL,
  ADD COLUMN repo_token VARCHAR(500) DEFAULT NULL,
  ADD COLUMN branch VARCHAR(100) DEFAULT 'main',
  ADD COLUMN install_cmd VARCHAR(500) DEFAULT NULL,
  ADD COLUMN build_cmd VARCHAR(500) DEFAULT NULL,
  ADD COLUMN restart_cmd VARCHAR(500) DEFAULT NULL,
  ADD COLUMN auto_deploy TINYINT(1) DEFAULT 0,
  ADD COLUMN last_commit VARCHAR(64) DEFAULT NULL,
  ADD COLUMN last_deployed_at DATETIME DEFAULT NULL;

ALTER TABLE deploy_logs
  ADD COLUMN connection_id INT DEFAULT NULL,
  ADD COLUMN commit_before VARCHAR(64) DEFAULT NULL,
  ADD COLUMN commit_after VARCHAR(64) DEFAULT NULL,
  ADD COLUMN branch VARCHAR(100) DEFAULT NULL,
  ADD COLUMN log_text LONGTEXT DEFAULT NULL;
